### PR TITLE
NO-ISSUE: Fix pagination render method

### LINKED ISSUE #163: [Bug] Pagination: Should not show ellipsis between consecutive pages
## Description

When using the pagination component, ellipses (…) are rendered between consecutive page numbers, which should not happen. Ellipses should only appear when there is a gap between non-adjacent page numbers.

## Steps to reproduce

1. Render the pagination component with a total of multiple pages (e.g. 19 pages).
2. Go to last page 
3. Use previous button
4. Click Page 1 

## Expected Behaviour

Ellipses should only appear when there is a gap between page numbers.

## Actual Behaviour

The pagination renders ellipses even when page numbers are consecutive.

## Screenshots

Image

## Environment

- **Package version(s)**: 1.0.0-beta.46
- **Operating System**: MacOS
- **Browser name and version**: Brave

### PR DESCRIPTION
**Pull request by enesuno**
## Description

Refactored the `getPageNumbers` utility function
Updated the `Pagination` component's render method

## Issue

Fixes #163 

## Screenshots

https://github.com/user-attachments/assets/39c3e7c5-a461-473c-8177-ada6346fab1a

## Type of change

- [ ] Feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Refactor
- [ ] Chore
- [ ] Documentation
- [ ] Tests
- [ ] Other (please specify):

## Check requirements

- [x] The code follows the project's coding standards and guidelines
- [ ] Documentation is updated accordingly
- [x] All existing tests are passing
- [x] I have added new tests to cover the changes

## Live Preview

https://daimlertruck.github.io/DT-DDS/PR-166

### CODE REVIEW

File: packages/react-packages/pagination/src/Pagination.tsx [hunk 1]
```diff
@@ -16,6 +16,26 @@ import {
...
 import { getPageNumbers } from './utils';
 
+const renderPage = (
+  page: number,
+  isThisPage: boolean,
+  handleClick: (page: number) => void
+) => (
+  <PaginationPageButtonStyled
+    $isActive={isThisPage}
+    aria-current={isThisPage ? 'page' : false}
```
Comment (catiaraminhos) [inline packages/react-packages/pagination/src/Pagination.tsx]: Nice one!
