### PR TITLE
NO-ISSUE: Fix SelectOption styling

### LINKED ISSUE #162: [Bug] MultiSelect: Options are rendered with wrong styling and interactivity does not work
## Description

The design of multi select is broken.  The checkboxes are misplaced and the click do not work properly 

## Steps to reproduce

1. Render a select with multi option enabled

## Expected Behavior

Image

## Actual Behavior

Image

## Environment

- **Package version(s)**: 1.0.0-beta.96
- **Operating System**: MacOS
- **Browser name and version**: Brave

### PR DESCRIPTION
**Pull request by enesuno**
## Description

Updated SelectOption stying
Corrected the usage of Checkbox's component API

## Issue

Fixes #162 

## Screenshots

Captura de ecrã 2026-02-03, às 22 57 55

## Type of change

- [ ] Feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Refactor
- [ ] Chore
- [ ] Documentation
- [ ] Tests
- [ ] Other (please specify):

## Check requirements

- [x] The code follows the project's coding standards and guidelines
- [ ] Documentation is updated accordingly
- [x] All existing tests are passing
- [ ] I have added new tests to cover the changes

## Live Preview

https://daimlertruck.github.io/DT-DDS/PR-165

### CODE REVIEW

File: packages/react-packages/select/src/components/SelectOption.tsx [hunk 1]
```diff
@@ -36,13 +36,13 @@ export const SelectOption = ({
       isDisabled={isDisabled}
       isHighlighted={isHighlighted}
       isSelected={isSelected}
-      style={{ ...style, ...(isMulti ? { padding: 0 } : {}) }}
+      style={{ ...style, ...(isMulti ? { padding: 16 } : {}) }}
```
Comment (diiogocosta) [inline packages/react-packages/select/src/components/SelectOption.tsx]:
```suggestion
      style={{ ...style, ...(isMulti ? { padding: theme.spacing['2xs'] } : {}) }}
```

suggestion, use the spacing variable to have this standard, the theme is acessible from the hook `const theme = useTheme();`

**Review by diiogocosta — APPROVED** [review]
